version: "2.4"
services:
  starlink_exporter:
    image: "ghcr.io/danopstech/starlink_exporter:latest"
    ports:
      - "9817:9817"
    networks:
      lannet:
        ipv4_address: 10.99.99.2

  speedtest_exporter:
    image: "ghcr.io/danopstech/speedtest_exporter:latest"
    ports:
      - "9090:9090"
    networks:
      lannet:
        ipv4_address: 10.99.99.3

  blackbox:
    image: "ghcr.io/danopstech/blackbox_exporter:latest"
    user: "root"
    ports:
      - "9115:9115"
    logging:
      driver: json-file
    volumes:
      - 'blackbox-config:/etc/blackbox_exporter'
    networks:
      lannet:
        ipv4_address: 10.99.99.4

  prometheus:
    image: "ghcr.io/danopstech/prometheus:latest"
    user: "root"
    ports:
      - "9090:9090"
    volumes:
      - 'prometheus-config:/etc/prometheus'
      - 'prometheus-data:/prometheus'
    logging:
      driver: json-file
    networks:
      lannet:
        ipv4_address: 10.99.99.5

  grafana:
    image: "ghcr.io/danopstech/grafana:latest"
    user: "root"
    ports:
      - "3000:3000"
    logging:
      driver: json-file
    environment:
      - GF_INSTALL_PLUGINS=ae3e-plotly-panel
      - GF_LOG_CONSOLE_LEVEL=warn
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - 'grafana-config:/etc/grafana/provisioning/'
    networks:
      lannet:
        ipv4_address: 10.99.99.6

  api:
    image: "docker.io/benkotvis/starlink-api:0.0.4"
    user: "root"
    ports:
      - "5007:5007"
    logging:
      driver: json-file
    environment:
      - ASPNETCORE_URLS=http://+:5007
    volumes:
      - 'grafana-data:/app/grafana-data'
      - 'grafana-config:/app/grafana-config'
      - 'prometheus-data:/app/prometheus-data'
      - 'prometheus-config:/app/prometheus-config'   
      - 'blackbox-config:/app/blackbox-config' 
    networks:
      lannet:
        ipv4_address: 10.99.99.7

volumes:
  blackbox-config:
    driver: local
  prometheus-config:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  grafana-config:
    driver: local

networks:
  lannet:
    driver: bridge
    driver_opts:
      com.cradlepoint.network.bridge.uuid: 00000002-0d93-319d-8220-4a1fb0372b51
    ipam:
      driver: default
      config:
        - subnet: 10.99.99.0/24
          gateway: 10.99.99.1